name: Monthly Forecast Update

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the 1st day of each month
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data download script
        run: python src/download_data.py

      - name: Run forecasting script
        run: python forecast.py
        
      - name: Upload data folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/
      - name: Upload Forecasts (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: forecasts
          path: forecasts/
      - name: Push forecasts to private branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b forecasts-branch || git checkout forecasts-branch
          git add forecasts/
          git commit -m "Update forecasts for $(date +'%Y-%m')"
          git push origin forecasts-branch