name: Monthly Forecast Update

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the 1st day of each month
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data download script
        run: python src/download_data.py

      - name: Run forecasting script
        run: python forecast.py
        
      - name: Upload data folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/

      - name: Upload Forecasts (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: forecasts
          path: forecasts/

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Push updated forecasts
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"

          # Fetch all branches from remote
          git fetch --all

          # Checkout the branch if it exists, else create it
          git checkout forecasts-branch || git checkout -b forecasts-branch
          
          # List contents of forecasts directory for debugging
          ls -al forecasts/

          # Force Git to add all files (new or modified)
          git add -A

          # Check Git status
          git status
          
          # Add the forecasts directory only if it exists
          if [ -d "forecasts" ]; then
              git add forecasts/
          else
              echo "forecasts directory does not exist, skipping git add."
          fi

          # Commit and push changes if there are any
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update forecasts for $(date +'%Y-%m')"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/PakAndrey/Canada-RE-forecasting.git forecasts-branch
          fi